// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lab.proto

package labgo

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Path struct {
	// Path Segments and File Name.
	Path                 []string `protobuf:"bytes,1,rep,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Path) Reset()         { *m = Path{} }
func (m *Path) String() string { return proto.CompactTextString(m) }
func (*Path) ProtoMessage()    {}
func (*Path) Descriptor() ([]byte, []int) {
	return fileDescriptor_a33572512533a9b1, []int{0}
}

func (m *Path) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Path.Unmarshal(m, b)
}
func (m *Path) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Path.Marshal(b, m, deterministic)
}
func (m *Path) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Path.Merge(m, src)
}
func (m *Path) XXX_Size() int {
	return xxx_messageInfo_Path.Size(m)
}
func (m *Path) XXX_DiscardUnknown() {
	xxx_messageInfo_Path.DiscardUnknown(m)
}

var xxx_messageInfo_Path proto.InternalMessageInfo

func (m *Path) GetPath() []string {
	if m != nil {
		return m.Path
	}
	return nil
}

type Delta struct {
	// File Offset.
	Offset uint64 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	// Bytes Removed.
	Remove []byte `protobuf:"bytes,2,opt,name=remove,proto3" json:"remove,omitempty"`
	// Bytes Added.
	Add                  []byte   `protobuf:"bytes,3,opt,name=add,proto3" json:"add,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Delta) Reset()         { *m = Delta{} }
func (m *Delta) String() string { return proto.CompactTextString(m) }
func (*Delta) ProtoMessage()    {}
func (*Delta) Descriptor() ([]byte, []int) {
	return fileDescriptor_a33572512533a9b1, []int{1}
}

func (m *Delta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Delta.Unmarshal(m, b)
}
func (m *Delta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Delta.Marshal(b, m, deterministic)
}
func (m *Delta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Delta.Merge(m, src)
}
func (m *Delta) XXX_Size() int {
	return xxx_messageInfo_Delta.Size(m)
}
func (m *Delta) XXX_DiscardUnknown() {
	xxx_messageInfo_Delta.DiscardUnknown(m)
}

var xxx_messageInfo_Delta proto.InternalMessageInfo

func (m *Delta) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *Delta) GetRemove() []byte {
	if m != nil {
		return m.Remove
	}
	return nil
}

func (m *Delta) GetAdd() []byte {
	if m != nil {
		return m.Add
	}
	return nil
}

type RGBA struct {
	Red                  uint32   `protobuf:"varint,1,opt,name=red,proto3" json:"red,omitempty"`
	Green                uint32   `protobuf:"varint,2,opt,name=green,proto3" json:"green,omitempty"`
	Blue                 uint32   `protobuf:"varint,3,opt,name=blue,proto3" json:"blue,omitempty"`
	Alpha                uint32   `protobuf:"varint,4,opt,name=alpha,proto3" json:"alpha,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RGBA) Reset()         { *m = RGBA{} }
func (m *RGBA) String() string { return proto.CompactTextString(m) }
func (*RGBA) ProtoMessage()    {}
func (*RGBA) Descriptor() ([]byte, []int) {
	return fileDescriptor_a33572512533a9b1, []int{2}
}

func (m *RGBA) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RGBA.Unmarshal(m, b)
}
func (m *RGBA) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RGBA.Marshal(b, m, deterministic)
}
func (m *RGBA) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RGBA.Merge(m, src)
}
func (m *RGBA) XXX_Size() int {
	return xxx_messageInfo_RGBA.Size(m)
}
func (m *RGBA) XXX_DiscardUnknown() {
	xxx_messageInfo_RGBA.DiscardUnknown(m)
}

var xxx_messageInfo_RGBA proto.InternalMessageInfo

func (m *RGBA) GetRed() uint32 {
	if m != nil {
		return m.Red
	}
	return 0
}

func (m *RGBA) GetGreen() uint32 {
	if m != nil {
		return m.Green
	}
	return 0
}

func (m *RGBA) GetBlue() uint32 {
	if m != nil {
		return m.Blue
	}
	return 0
}

func (m *RGBA) GetAlpha() uint32 {
	if m != nil {
		return m.Alpha
	}
	return 0
}

type Draw struct {
	Color                *RGBA    `protobuf:"bytes,1,opt,name=color,proto3" json:"color,omitempty"`
	Size                 uint32   `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Points               []int32  `protobuf:"varint,3,rep,packed,name=points,proto3" json:"points,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Draw) Reset()         { *m = Draw{} }
func (m *Draw) String() string { return proto.CompactTextString(m) }
func (*Draw) ProtoMessage()    {}
func (*Draw) Descriptor() ([]byte, []int) {
	return fileDescriptor_a33572512533a9b1, []int{3}
}

func (m *Draw) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Draw.Unmarshal(m, b)
}
func (m *Draw) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Draw.Marshal(b, m, deterministic)
}
func (m *Draw) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Draw.Merge(m, src)
}
func (m *Draw) XXX_Size() int {
	return xxx_messageInfo_Draw.Size(m)
}
func (m *Draw) XXX_DiscardUnknown() {
	xxx_messageInfo_Draw.DiscardUnknown(m)
}

var xxx_messageInfo_Draw proto.InternalMessageInfo

func (m *Draw) GetColor() *RGBA {
	if m != nil {
		return m.Color
	}
	return nil
}

func (m *Draw) GetSize() uint32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Draw) GetPoints() []int32 {
	if m != nil {
		return m.Points
	}
	return nil
}

type Chat struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Chat) Reset()         { *m = Chat{} }
func (m *Chat) String() string { return proto.CompactTextString(m) }
func (*Chat) ProtoMessage()    {}
func (*Chat) Descriptor() ([]byte, []int) {
	return fileDescriptor_a33572512533a9b1, []int{4}
}

func (m *Chat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Chat.Unmarshal(m, b)
}
func (m *Chat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Chat.Marshal(b, m, deterministic)
}
func (m *Chat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Chat.Merge(m, src)
}
func (m *Chat) XXX_Size() int {
	return xxx_messageInfo_Chat.Size(m)
}
func (m *Chat) XXX_DiscardUnknown() {
	xxx_messageInfo_Chat.DiscardUnknown(m)
}

var xxx_messageInfo_Chat proto.InternalMessageInfo

func (m *Chat) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func init() {
	proto.RegisterType((*Path)(nil), "lab.Path")
	proto.RegisterType((*Delta)(nil), "lab.Delta")
	proto.RegisterType((*RGBA)(nil), "lab.RGBA")
	proto.RegisterType((*Draw)(nil), "lab.Draw")
	proto.RegisterType((*Chat)(nil), "lab.Chat")
}

func init() { proto.RegisterFile("lab.proto", fileDescriptor_a33572512533a9b1) }

var fileDescriptor_a33572512533a9b1 = []byte{
	// 297 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x2c, 0x91, 0x41, 0x6b, 0xfa, 0x40,
	0x10, 0xc5, 0x89, 0x49, 0xe4, 0x9f, 0xf9, 0x57, 0x90, 0x45, 0x4a, 0xf0, 0xd2, 0x90, 0x53, 0x4e,
	0x11, 0xda, 0x4f, 0x60, 0x14, 0x4a, 0xc1, 0x83, 0xec, 0xc5, 0xd2, 0xdb, 0xac, 0x8e, 0x6e, 0x60,
	0x75, 0xc3, 0x66, 0xad, 0xa5, 0x9f, 0xbe, 0xcc, 0x26, 0xb7, 0xdf, 0x7b, 0x3b, 0xfb, 0x66, 0x67,
	0x16, 0x32, 0x83, 0xaa, 0xee, 0x9c, 0xf5, 0x56, 0xc4, 0x06, 0x55, 0xb9, 0x84, 0x64, 0x8f, 0x5e,
	0x0b, 0x01, 0x49, 0x87, 0x5e, 0xe7, 0x51, 0x11, 0x57, 0x99, 0x0c, 0x5c, 0x7e, 0x40, 0xba, 0x25,
	0xe3, 0x51, 0x3c, 0xc3, 0xd4, 0x9e, 0xcf, 0x3d, 0xf9, 0x3c, 0x2a, 0xa2, 0x2a, 0x91, 0xa3, 0x62,
	0xdf, 0xd1, 0xd5, 0x7e, 0x53, 0x3e, 0x29, 0xa2, 0xea, 0x49, 0x8e, 0x4a, 0xcc, 0x21, 0xc6, 0xd3,
	0x29, 0x8f, 0x83, 0xc9, 0x58, 0x7e, 0x42, 0x22, 0xdf, 0x9b, 0x35, 0x9f, 0x38, 0x3a, 0x85, 0x98,
	0x99, 0x64, 0x14, 0x0b, 0x48, 0x2f, 0x8e, 0xe8, 0x16, 0x22, 0x66, 0x72, 0x10, 0xfc, 0x1c, 0x65,
	0xee, 0x14, 0x22, 0x66, 0x32, 0x30, 0x57, 0xa2, 0xe9, 0x34, 0xe6, 0xc9, 0x50, 0x19, 0x44, 0x79,
	0x80, 0x64, 0xeb, 0xf0, 0x21, 0x5e, 0x20, 0x3d, 0x5a, 0x63, 0x5d, 0xc8, 0xfe, 0xff, 0x9a, 0xd5,
	0x3c, 0x28, 0xf7, 0x94, 0x83, 0xcf, 0x91, 0x7d, 0xfb, 0x4b, 0x63, 0x9f, 0xc0, 0x62, 0x09, 0xd3,
	0xce, 0xb6, 0x37, 0xdf, 0xe7, 0x71, 0x11, 0x57, 0x69, 0x33, 0x99, 0x47, 0x72, 0x74, 0x78, 0x33,
	0x1b, 0x8d, 0x9e, 0xef, 0x79, 0xfa, 0x19, 0x46, 0xcf, 0x64, 0xe0, 0xa6, 0x81, 0xc5, 0xd1, 0x5e,
	0x6b, 0x34, 0xe4, 0x35, 0xb5, 0xf8, 0x40, 0x47, 0xdc, 0xaf, 0xf9, 0xb7, 0x43, 0xb5, 0xe7, 0xe5,
	0x7e, 0x15, 0x97, 0xd6, 0xeb, 0xbb, 0xaa, 0x8f, 0xf6, 0xba, 0x5a, 0x8f, 0x65, 0x07, 0x74, 0xb4,
	0xdb, 0x6d, 0x56, 0x06, 0xd5, 0xc5, 0xaa, 0x69, 0xf8, 0x85, 0xb7, 0xbf, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xb3, 0x8d, 0x8b, 0x5c, 0x92, 0x01, 0x00, 0x00,
}
